name: Linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  testing:

    name: Container ${{ matrix.container }}
    runs-on: ubuntu-latest

    container:
      image: ${{ matrix.container }}

    strategy:
      matrix:
        container: [
          "nvidia/cuda:12.6.1-devel-ubuntu20.04",
          "nvidia/cuda:12.6.1-devel-ubuntu22.04",
          "nvidia/cuda:12.6.1-devel-ubuntu24.04",
          #"nvidia/cuda:11.2.2-devel-ubuntu20.04",
          ]

    steps:
    - uses: actions/checkout@v4

    - name: Install cmake
      run: apt update && apt install cmake

    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_CUDA_ARCHITECTURES=all-major

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    #- name: Test
    #  working-directory: ${{github.workspace}}/build
    #  # Execute tests defined by the CMake configuration.
    #  # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
    #  run: ctest -C ${{env.BUILD_TYPE}}

